logging:
  level:
    org.org.springframework.web: WARN
    com.ote.test: INFO

server:
  port: ${PORT:8080}

spring:
  application.name: Secret-Service
  main.banner-mode: LOG
  datasource:
    url: jdbc:postgresql://localhost:5432/secrets
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    initialize: true
#    initialize: false
    continue-on-error: true
    platform: postgres
  jpa:
    show-sql: false
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQL92Dialect
    hibernate:
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#      ddl-auto: none
      ddl-auto: create-drop